labels: [Profile]
fields:
  - type: dropdown
    attributes:
      label: "Select Topic Area"
      description: "Choose the topic you want to discuss:"
      options:
        - "Question"
        - "Product Feedback"
        - "Bug"
        - "Show & Tell"
        - "General"
      placeholder: "Please select a topic"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Discussion Details"
      description: "Provide details about your discussion:"
      placeholder: "Start your discussion here..."
      rows: 5
    validations:
      required: true
